### ISSUE TITLE
Installing into QGIS version 3.16.3-Hannover

### ISSUE THREAD

**Issue by T-G-M** [enricofer/QgisODK#19]
Couldn't load plugin 'QgisODK-master' due to an error when calling its classFactory() method 

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead.

**Comment by enricofer** [comment]
The plugin has not been (fully) migrated to qgis 3 yet. Maybe in the next future.

**Comment by lognaturel** [comment]
@enricofer do you have plans to continue supporting QgisODK? There's a fork/rework at https://github.com/shivareddyiirs/QRealTime that has been active over the years. Perhaps you'd be interested in collaborating on that? ODK Central support is coming soon: https://github.com/shivareddyiirs/QRealTime/tree/ODK_Central . There's also a refactor project under way.

**Comment by enricofer** [comment]
Hi @lognaturel  I worked on a QGIS3 migration https://github.com/enricofer/QgisODK/tree/QGIS3_migration but it has some Qt5 issues https://github.com/enricofer/QgisODK/issues/18. At the moment I'm not working on it and I recommend QGIS3 users to look around for other solutions. But one should never say never. Anyway thanks for your interest.
