### ISSUE TITLE
Import Qgis Label

### ISSUE THREAD

**Issue by alexfibrea** [enricofer/QgisODK#7]
is it possible to import the labels from the database?

Posgresql

QGIS screenshot 
![image](https://user-images.githubusercontent.com/26411199/33426817-6a9f7d28-d5c3-11e7-8541-7007bb939831.png)

**Comment by enricofer** [comment]
This is an interesting feature request.
I suppose you are doing this using loading postgres table and using "value relation" form widget. Do You?

**Comment by alexfibrea** [comment]
exactly

**Comment by alexfibrea** [comment]
I would also like to import from Postgresql the "ODK Type"

picture
text
GeoPoint

to avoid having to enter each time

and why not .. also save the XML files in the postgresql database

**Comment by enricofer** [comment]
Auto setting qgis form field widgets from datasource types goes far beyond the plugin scope.
I think you have to hire some core developer to do that

**Comment by enricofer** [comment]
https://github.com/enricofer/QgisODK/commit/a81137c9ac60571a9b7c34db7ead93c8449dd2c0
